export interface LabValue {
  name: string;
  abbreviation?: string;
  normalRange: string;
  unit: string;
  criticalLow?: string;
  criticalHigh?: string;
  notes?: string;
}

export interface LabCategory {
  id: string;
  title: string;
  description: string;
  icon: string;
  values: LabValue[];
}

export const labCategories: LabCategory[] = [
  {
    id: 'cbc',
    title: 'Complete Blood Count (CBC)',
    description:
      'Measures the cellular components of blood, used to assess overall health and detect a wide range of disorders including anemia, infection, and leukemia.',
    icon: '🩸',
    values: [
      {
        name: 'White Blood Cells',
        abbreviation: 'WBC',
        normalRange: '4,500 – 11,000',
        unit: 'cells/µL',
        criticalLow: '< 2,000',
        criticalHigh: '> 30,000',
        notes: 'Elevated in infection, leukemia; decreased in bone marrow suppression.',
      },
      {
        name: 'Red Blood Cells',
        abbreviation: 'RBC',
        normalRange: '4.5 – 5.5 (M), 4.0 – 5.0 (F)',
        unit: 'million cells/µL',
        notes: 'Decreased in anemia; elevated in polycythemia.',
      },
      {
        name: 'Hemoglobin',
        abbreviation: 'Hgb / Hb',
        normalRange: '13.5 – 17.5 (M), 12.0 – 15.5 (F)',
        unit: 'g/dL',
        criticalLow: '< 7.0',
        criticalHigh: '> 20.0',
        notes: 'Primary oxygen-carrying protein. Key indicator for anemia.',
      },
      {
        name: 'Hematocrit',
        abbreviation: 'Hct',
        normalRange: '41 – 53% (M), 36 – 46% (F)',
        unit: '%',
        criticalLow: '< 21%',
        criticalHigh: '> 60%',
        notes: 'Percentage of blood volume occupied by red blood cells.',
      },
      {
        name: 'Mean Corpuscular Volume',
        abbreviation: 'MCV',
        normalRange: '80 – 100',
        unit: 'fL',
        notes: 'Average size of RBCs. Low = microcytic; High = macrocytic.',
      },
      {
        name: 'Mean Corpuscular Hemoglobin',
        abbreviation: 'MCH',
        normalRange: '27 – 33',
        unit: 'pg',
        notes: 'Average amount of hemoglobin per RBC.',
      },
      {
        name: 'Mean Corpuscular Hemoglobin Concentration',
        abbreviation: 'MCHC',
        normalRange: '32 – 36',
        unit: 'g/dL',
        notes: 'Concentration of hemoglobin in RBCs. Low = hypochromic.',
      },
      {
        name: 'Platelets',
        abbreviation: 'PLT',
        normalRange: '150,000 – 400,000',
        unit: 'cells/µL',
        criticalLow: '< 50,000',
        criticalHigh: '> 1,000,000',
        notes: 'Essential for clotting. Decreased in thrombocytopenia.',
      },
      {
        name: 'Neutrophils',
        normalRange: '55 – 70',
        unit: '%',
        notes: 'First responders to bacterial infection.',
      },
      {
        name: 'Lymphocytes',
        normalRange: '20 – 40',
        unit: '%',
        notes: 'Key in viral infections and immune response.',
      },
      {
        name: 'Monocytes',
        normalRange: '2 – 8',
        unit: '%',
        notes: 'Involved in chronic inflammation.',
      },
      {
        name: 'Eosinophils',
        normalRange: '1 – 4',
        unit: '%',
        notes: 'Elevated in allergies and parasitic infections.',
      },
      {
        name: 'Basophils',
        normalRange: '0.5 – 1',
        unit: '%',
        notes: 'Involved in allergic reactions.',
      },
    ],
  },
  {
    id: 'bmp',
    title: 'Basic Metabolic Panel (BMP)',
    description:
      'Provides key information about kidney function, blood sugar, and electrolyte and acid/base balance.',
    icon: '⚗️',
    values: [
      {
        name: 'Sodium',
        abbreviation: 'Na⁺',
        normalRange: '136 – 145',
        unit: 'mEq/L',
        criticalLow: '< 120',
        criticalHigh: '> 160',
        notes: 'Primary extracellular cation. Regulates fluid balance.',
      },
      {
        name: 'Potassium',
        abbreviation: 'K⁺',
        normalRange: '3.5 – 5.0',
        unit: 'mEq/L',
        criticalLow: '< 2.5',
        criticalHigh: '> 6.5',
        notes: 'Critical for cardiac function. Dysrhythmias possible at extreme values.',
      },
      {
        name: 'Chloride',
        abbreviation: 'Cl⁻',
        normalRange: '98 – 106',
        unit: 'mEq/L',
        criticalLow: '< 80',
        criticalHigh: '> 115',
        notes: 'Major extracellular anion; follows sodium in fluid balance.',
      },
      {
        name: 'Carbon Dioxide (Bicarbonate)',
        abbreviation: 'CO₂ / HCO₃⁻',
        normalRange: '22 – 29',
        unit: 'mEq/L',
        criticalLow: '< 10',
        criticalHigh: '> 40',
        notes: 'Reflects acid-base status and bicarbonate level.',
      },
      {
        name: 'Blood Urea Nitrogen',
        abbreviation: 'BUN',
        normalRange: '7 – 20',
        unit: 'mg/dL',
        criticalHigh: '> 100',
        notes: 'Kidney waste product. Elevated in renal impairment or dehydration.',
      },
      {
        name: 'Creatinine',
        abbreviation: 'Cr',
        normalRange: '0.7 – 1.3 (M), 0.5 – 1.1 (F)',
        unit: 'mg/dL',
        criticalHigh: '> 10.0',
        notes: 'More specific marker of kidney function than BUN.',
      },
      {
        name: 'Glucose',
        abbreviation: 'GLU',
        normalRange: '70 – 100 (fasting)',
        unit: 'mg/dL',
        criticalLow: '< 40',
        criticalHigh: '> 500',
        notes: 'Primary energy source. Key in diabetes management.',
      },
      {
        name: 'Calcium',
        abbreviation: 'Ca²⁺',
        normalRange: '8.5 – 10.2',
        unit: 'mg/dL',
        criticalLow: '< 6.0',
        criticalHigh: '> 13.0',
        notes: 'Important for bone health, muscle contraction, and nerve function.',
      },
    ],
  },
  {
    id: 'lft',
    title: 'Liver Function Tests (LFTs)',
    description:
      'Assess liver health by measuring proteins, enzymes, and bilirubin produced or metabolized by the liver.',
    icon: '🫀',
    values: [
      {
        name: 'Alanine Aminotransferase',
        abbreviation: 'ALT (SGPT)',
        normalRange: '7 – 56',
        unit: 'U/L',
        notes: 'More specific to liver damage than AST.',
      },
      {
        name: 'Aspartate Aminotransferase',
        abbreviation: 'AST (SGOT)',
        normalRange: '10 – 40',
        unit: 'U/L',
        notes: 'Elevated in liver and cardiac damage.',
      },
      {
        name: 'Alkaline Phosphatase',
        abbreviation: 'ALP',
        normalRange: '44 – 147',
        unit: 'U/L',
        notes: 'Elevated in liver/bile duct disease and bone disorders.',
      },
      {
        name: 'Total Bilirubin',
        abbreviation: 'T. Bili',
        normalRange: '0.1 – 1.2',
        unit: 'mg/dL',
        criticalHigh: '> 15.0',
        notes: 'Breakdown product of hemoglobin. Elevated in jaundice.',
      },
      {
        name: 'Direct Bilirubin',
        abbreviation: 'D. Bili',
        normalRange: '0.0 – 0.3',
        unit: 'mg/dL',
        notes: 'Conjugated bilirubin; elevated in hepatic/post-hepatic causes.',
      },
      {
        name: 'Indirect Bilirubin',
        abbreviation: 'I. Bili',
        normalRange: '0.1 – 1.0',
        unit: 'mg/dL',
        notes: 'Unconjugated bilirubin; elevated in hemolytic causes.',
      },
      {
        name: 'Albumin',
        abbreviation: 'Alb',
        normalRange: '3.5 – 5.0',
        unit: 'g/dL',
        criticalLow: '< 1.5',
        notes: 'Major plasma protein; low levels indicate malnutrition or chronic liver disease.',
      },
      {
        name: 'Total Protein',
        abbreviation: 'TP',
        normalRange: '6.3 – 8.2',
        unit: 'g/dL',
        notes: 'Sum of albumin and globulin.',
      },
      {
        name: 'Gamma-Glutamyl Transferase',
        abbreviation: 'GGT',
        normalRange: '8 – 61 (M), 5 – 36 (F)',
        unit: 'U/L',
        notes: 'Sensitive marker for alcohol use and bile duct disease.',
      },
    ],
  },
  {
    id: 'coagulation',
    title: 'Coagulation Studies',
    description:
      "Evaluate the blood's ability to clot properly. Critical for patients on anticoagulation therapy.",
    icon: '🧪',
    values: [
      {
        name: 'Prothrombin Time',
        abbreviation: 'PT',
        normalRange: '11 – 13.5',
        unit: 'seconds',
        criticalHigh: '> 30',
        notes: 'Measures extrinsic coagulation pathway. Prolonged with warfarin use.',
      },
      {
        name: 'International Normalized Ratio',
        abbreviation: 'INR',
        normalRange: '0.8 – 1.1',
        unit: '(ratio)',
        criticalHigh: '> 5.0',
        notes: 'Standardized PT ratio. Therapeutic range for anticoagulation: 2.0–3.0.',
      },
      {
        name: 'Partial Thromboplastin Time',
        abbreviation: 'PTT / aPTT',
        normalRange: '25 – 35',
        unit: 'seconds',
        criticalHigh: '> 100',
        notes: 'Measures intrinsic coagulation pathway. Prolonged with heparin therapy.',
      },
      {
        name: 'Fibrinogen',
        normalRange: '200 – 400',
        unit: 'mg/dL',
        criticalLow: '< 50',
        notes: 'Clotting protein; decreased in DIC and liver failure.',
      },
      {
        name: 'D-Dimer',
        normalRange: '< 0.5',
        unit: 'µg/mL FEU',
        notes: 'Elevated in DVT, PE, and DIC. Used to rule out thrombosis.',
      },
      {
        name: 'Bleeding Time',
        normalRange: '2 – 9',
        unit: 'minutes',
        notes: 'Evaluates platelet function and vascular response.',
      },
    ],
  },
  {
    id: 'abg',
    title: 'Arterial Blood Gas (ABG)',
    description:
      'Measures oxygen and carbon dioxide levels and acid-base balance in arterial blood. Essential for managing respiratory conditions.',
    icon: '💨',
    values: [
      {
        name: 'pH',
        normalRange: '7.35 – 7.45',
        unit: '',
        criticalLow: '< 7.20',
        criticalHigh: '> 7.60',
        notes: 'Reflects overall acid-base status. < 7.35 = acidosis; > 7.45 = alkalosis.',
      },
      {
        name: 'Partial Pressure of Oxygen',
        abbreviation: 'PaO₂',
        normalRange: '75 – 100',
        unit: 'mmHg',
        criticalLow: '< 40',
        notes: 'Dissolved oxygen in arterial blood. < 60 = hypoxemia.',
      },
      {
        name: 'Partial Pressure of Carbon Dioxide',
        abbreviation: 'PaCO₂',
        normalRange: '35 – 45',
        unit: 'mmHg',
        criticalLow: '< 20',
        criticalHigh: '> 70',
        notes: 'Respiratory component. Elevated = hypoventilation; Decreased = hyperventilation.',
      },
      {
        name: 'Bicarbonate',
        abbreviation: 'HCO₃⁻',
        normalRange: '22 – 26',
        unit: 'mEq/L',
        criticalLow: '< 10',
        criticalHigh: '> 40',
        notes: 'Metabolic component of acid-base balance.',
      },
      {
        name: 'Oxygen Saturation',
        abbreviation: 'SaO₂',
        normalRange: '95 – 100',
        unit: '%',
        criticalLow: '< 85%',
        notes: 'Percentage of hemoglobin saturated with oxygen.',
      },
      {
        name: 'Base Excess / Deficit',
        abbreviation: 'BE',
        normalRange: '-2 to +2',
        unit: 'mEq/L',
        notes: 'Indicates metabolic component. Negative = metabolic acidosis; Positive = metabolic alkalosis.',
      },
    ],
  },
  {
    id: 'thyroid',
    title: 'Thyroid Function Tests',
    description:
      'Assess thyroid gland activity, commonly ordered to diagnose hyperthyroidism and hypothyroidism.',
    icon: '🦋',
    values: [
      {
        name: 'Thyroid-Stimulating Hormone',
        abbreviation: 'TSH',
        normalRange: '0.4 – 4.0',
        unit: 'mIU/L',
        criticalLow: '< 0.01',
        criticalHigh: '> 10.0',
        notes: 'Best screening test for thyroid dysfunction. High TSH = hypothyroidism; Low TSH = hyperthyroidism.',
      },
      {
        name: 'Free Thyroxine',
        abbreviation: 'Free T4',
        normalRange: '0.8 – 1.8',
        unit: 'ng/dL',
        notes: 'Active form of T4. Elevated in hyperthyroidism; Low in hypothyroidism.',
      },
      {
        name: 'Free Triiodothyronine',
        abbreviation: 'Free T3',
        normalRange: '2.3 – 4.2',
        unit: 'pg/mL',
        notes: 'Most active thyroid hormone. Useful in diagnosing T3 toxicosis.',
      },
      {
        name: 'Total T4 (Thyroxine)',
        abbreviation: 'T4',
        normalRange: '5.0 – 12.0',
        unit: 'µg/dL',
        notes: 'Includes bound and free T4.',
      },
      {
        name: 'Total T3 (Triiodothyronine)',
        abbreviation: 'T3',
        normalRange: '80 – 200',
        unit: 'ng/dL',
        notes: 'Useful in diagnosing hyperthyroidism when T4 is normal.',
      },
      {
        name: 'Thyroid Peroxidase Antibodies',
        abbreviation: 'TPO Ab',
        normalRange: '< 35',
        unit: 'IU/mL',
        notes: 'Elevated in Hashimoto\'s thyroiditis and Graves\' disease.',
      },
    ],
  },
  {
    id: 'lipids',
    title: 'Lipid Panel',
    description:
      'Measures types of fats in the blood to assess cardiovascular risk. Fasting for 9–12 hours is typically required.',
    icon: '❤️',
    values: [
      {
        name: 'Total Cholesterol',
        normalRange: '< 200 (desirable)',
        unit: 'mg/dL',
        notes: '200–239 = borderline high; ≥ 240 = high.',
      },
      {
        name: 'Low-Density Lipoprotein',
        abbreviation: 'LDL',
        normalRange: '< 100 (optimal)',
        unit: 'mg/dL',
        notes: '"Bad" cholesterol. Major risk factor for heart disease.',
      },
      {
        name: 'High-Density Lipoprotein',
        abbreviation: 'HDL',
        normalRange: '≥ 60 (optimal)',
        unit: 'mg/dL',
        notes: '"Good" cholesterol. ≥ 60 is protective; < 40 (M) / < 50 (F) is low.',
      },
      {
        name: 'Triglycerides',
        abbreviation: 'TG',
        normalRange: '< 150',
        unit: 'mg/dL',
        criticalHigh: '> 500',
        notes: '150–199 = borderline high; ≥ 200 = high; ≥ 500 = very high.',
      },
      {
        name: 'VLDL Cholesterol',
        abbreviation: 'VLDL',
        normalRange: '2 – 30',
        unit: 'mg/dL',
        notes: 'Carries triglycerides. Calculated as TG ÷ 5.',
      },
      {
        name: 'Non-HDL Cholesterol',
        normalRange: '< 130',
        unit: 'mg/dL',
        notes: 'Total cholesterol minus HDL. Better predictor of CVD risk.',
      },
    ],
  },
  {
    id: 'cardiac',
    title: 'Cardiac Markers',
    description:
      'Proteins released into the bloodstream when heart muscle is damaged. Critical in diagnosing myocardial infarction (heart attack).',
    icon: '💓',
    values: [
      {
        name: 'Troponin I',
        abbreviation: 'cTnI',
        normalRange: '< 0.04',
        unit: 'ng/mL',
        criticalHigh: '> 0.4',
        notes: 'Highly specific for cardiac muscle injury. Rises within 3–6 h; peaks 14–24 h.',
      },
      {
        name: 'Troponin T',
        abbreviation: 'cTnT',
        normalRange: '< 0.01',
        unit: 'ng/mL',
        notes: 'Similar to Troponin I; used in acute MI diagnosis.',
      },
      {
        name: 'High-Sensitivity Troponin',
        abbreviation: 'hsTn',
        normalRange: '< 14 (varies by lab)',
        unit: 'ng/L',
        notes: 'Detects very small amounts; allows earlier MI diagnosis.',
      },
      {
        name: 'Creatine Kinase-MB',
        abbreviation: 'CK-MB',
        normalRange: '< 3 – 5',
        unit: 'ng/mL',
        notes: 'Cardiac-specific isoform. Rises 3–6 h post-MI; useful for reinfarction.',
      },
      {
        name: 'Brain Natriuretic Peptide',
        abbreviation: 'BNP',
        normalRange: '< 100',
        unit: 'pg/mL',
        notes: 'Elevated in heart failure. Used to stratify HF severity.',
      },
      {
        name: 'NT-proBNP',
        normalRange: '< 125 (age < 75), < 450 (age ≥ 75)',
        unit: 'pg/mL',
        notes: 'More stable form of BNP fragment. Higher cutoffs than BNP.',
      },
      {
        name: 'Myoglobin',
        normalRange: '< 90 (M), < 75 (F)',
        unit: 'ng/mL',
        notes: 'Early marker of muscle damage but not cardiac-specific.',
      },
      {
        name: 'Creatine Kinase (Total)',
        abbreviation: 'CK / CPK',
        normalRange: '22 – 198 (M), 22 – 166 (F)',
        unit: 'U/L',
        notes: 'Total enzyme from muscle cells; elevated in MI, rhabdomyolysis, statin myopathy.',
      },
    ],
  },
  {
    id: 'urinalysis',
    title: 'Urinalysis (UA)',
    description:
      'Physical, chemical, and microscopic examination of urine. Used to detect kidney disease, UTI, and metabolic disorders.',
    icon: '🔬',
    values: [
      {
        name: 'Color',
        normalRange: 'Pale to dark yellow',
        unit: '',
        notes: 'Clear/colorless = overhydration; dark amber = dehydration; pink/red = hematuria or dye.',
      },
      {
        name: 'Clarity',
        normalRange: 'Clear',
        unit: '',
        notes: 'Turbid (cloudy) may indicate infection, cells, or crystals.',
      },
      {
        name: 'Specific Gravity',
        normalRange: '1.005 – 1.030',
        unit: '',
        notes: 'Measures urine concentration. < 1.005 = dilute; > 1.030 = concentrated.',
      },
      {
        name: 'pH',
        normalRange: '4.5 – 8.0',
        unit: '',
        notes: 'Typically slightly acidic (5–6). Affected by diet and disease.',
      },
      {
        name: 'Protein',
        normalRange: 'Negative / trace',
        unit: '',
        notes: 'Persistent proteinuria indicates kidney disease.',
      },
      {
        name: 'Glucose',
        normalRange: 'Negative',
        unit: '',
        notes: 'Present when blood glucose exceeds renal threshold (~180 mg/dL).',
      },
      {
        name: 'Ketones',
        normalRange: 'Negative',
        unit: '',
        notes: 'Present in diabetic ketoacidosis, starvation, or low-carb diet.',
      },
      {
        name: 'Blood / Hemoglobin',
        normalRange: 'Negative',
        unit: '',
        notes: 'Positive = hematuria (RBCs) or hemoglobinuria/myoglobinuria.',
      },
      {
        name: 'Nitrite',
        normalRange: 'Negative',
        unit: '',
        notes: 'Positive indicates presence of nitrite-reducing bacteria (gram-negative).',
      },
      {
        name: 'Leukocyte Esterase',
        normalRange: 'Negative',
        unit: '',
        notes: 'Positive indicates WBCs in urine (pyuria); suggests UTI.',
      },
      {
        name: 'White Blood Cells (microscopic)',
        normalRange: '0 – 5',
        unit: 'per HPF',
        notes: '> 5 WBCs/HPF = pyuria; suggests infection or kidney inflammation.',
      },
      {
        name: 'Red Blood Cells (microscopic)',
        normalRange: '0 – 3',
        unit: 'per HPF',
        notes: '> 3 RBCs/HPF = hematuria; investigate for stone, tumor, or glomerulonephritis.',
      },
      {
        name: 'Bacteria',
        normalRange: 'None',
        unit: '',
        notes: 'Any bacteria in properly collected specimen suggests UTI.',
      },
    ],
  },
  {
    id: 'electrolytes',
    title: 'Electrolytes & Minerals',
    description:
      'Minerals dissolved in blood and body fluids that carry an electrical charge. Essential for nerve, muscle, and organ function.',
    icon: '⚡',
    values: [
      {
        name: 'Sodium',
        abbreviation: 'Na⁺',
        normalRange: '136 – 145',
        unit: 'mEq/L',
        criticalLow: '< 120',
        criticalHigh: '> 160',
        notes: 'Regulates fluid balance and osmolarity.',
      },
      {
        name: 'Potassium',
        abbreviation: 'K⁺',
        normalRange: '3.5 – 5.0',
        unit: 'mEq/L',
        criticalLow: '< 2.5',
        criticalHigh: '> 6.5',
        notes: 'Critical for cardiac rhythm; dysrhythmias at extremes.',
      },
      {
        name: 'Chloride',
        abbreviation: 'Cl⁻',
        normalRange: '98 – 106',
        unit: 'mEq/L',
        criticalLow: '< 80',
        criticalHigh: '> 115',
        notes: 'Maintains fluid and acid-base balance.',
      },
      {
        name: 'Magnesium',
        abbreviation: 'Mg²⁺',
        normalRange: '1.7 – 2.2',
        unit: 'mg/dL',
        criticalLow: '< 1.0',
        criticalHigh: '> 4.9',
        notes: 'Essential for enzymatic reactions. Low in malnutrition and alcoholism.',
      },
      {
        name: 'Phosphorus / Phosphate',
        abbreviation: 'Phos / PO₄',
        normalRange: '2.5 – 4.5',
        unit: 'mg/dL',
        criticalLow: '< 1.0',
        criticalHigh: '> 8.9',
        notes: 'Important for bone health and energy metabolism.',
      },
      {
        name: 'Calcium',
        abbreviation: 'Ca²⁺',
        normalRange: '8.5 – 10.2',
        unit: 'mg/dL',
        criticalLow: '< 6.0',
        criticalHigh: '> 13.0',
        notes: 'Bone structure, muscle contraction, blood clotting.',
      },
      {
        name: 'Ionized Calcium',
        abbreviation: 'iCa',
        normalRange: '4.5 – 5.6',
        unit: 'mg/dL',
        criticalLow: '< 3.2',
        criticalHigh: '> 6.4',
        notes: 'The physiologically active form; more accurate than total calcium.',
      },
    ],
  },
  {
    id: 'renal',
    title: 'Renal Function Tests',
    description:
      'Assess how well the kidneys are filtering waste from the blood.',
    icon: '🫘',
    values: [
      {
        name: 'Blood Urea Nitrogen',
        abbreviation: 'BUN',
        normalRange: '7 – 20',
        unit: 'mg/dL',
        criticalHigh: '> 100',
        notes: 'Reflects protein metabolism and kidney excretion.',
      },
      {
        name: 'Creatinine',
        abbreviation: 'Cr',
        normalRange: '0.7 – 1.3 (M), 0.5 – 1.1 (F)',
        unit: 'mg/dL',
        criticalHigh: '> 10.0',
        notes: 'Stable marker of GFR; more specific than BUN.',
      },
      {
        name: 'BUN/Creatinine Ratio',
        normalRange: '10:1 – 20:1',
        unit: '(ratio)',
        notes: '> 20:1 = pre-renal azotemia; < 10:1 = intrinsic renal disease.',
      },
      {
        name: 'Estimated GFR',
        abbreviation: 'eGFR',
        normalRange: '≥ 60',
        unit: 'mL/min/1.73 m²',
        criticalLow: '< 15',
        notes: 'Estimated glomerular filtration rate. < 60 for > 3 months = CKD.',
      },
      {
        name: 'Uric Acid',
        normalRange: '3.4 – 7.0 (M), 2.4 – 6.0 (F)',
        unit: 'mg/dL',
        notes: 'Elevated in gout, renal failure, and tumor lysis syndrome.',
      },
      {
        name: 'Cystatin C',
        normalRange: '0.62 – 1.15',
        unit: 'mg/L',
        notes: 'Alternative GFR marker; less affected by muscle mass than creatinine.',
      },
    ],
  },
  {
    id: 'glucose',
    title: 'Glucose & Diabetes Tests',
    description:
      'Monitor blood glucose levels and long-term glycemic control in patients with or at risk for diabetes.',
    icon: '🍬',
    values: [
      {
        name: 'Fasting Blood Glucose',
        abbreviation: 'FBG',
        normalRange: '70 – 99',
        unit: 'mg/dL',
        criticalLow: '< 40',
        criticalHigh: '> 500',
        notes: '100–125 = prediabetes; ≥ 126 = diabetes (confirmed on repeat).',
      },
      {
        name: 'Random Blood Glucose',
        abbreviation: 'RBG',
        normalRange: '< 140 (post-meal)',
        unit: 'mg/dL',
        criticalLow: '< 40',
        criticalHigh: '> 500',
        notes: '≥ 200 with symptoms = diabetes.',
      },
      {
        name: 'Hemoglobin A1c',
        abbreviation: 'HbA1c / A1C',
        normalRange: '< 5.7%',
        unit: '%',
        notes: '5.7–6.4% = prediabetes; ≥ 6.5% = diabetes. Reflects 2–3 month average glucose.',
      },
      {
        name: '2-Hour Oral Glucose Tolerance Test',
        abbreviation: 'OGTT (2-hr)',
        normalRange: '< 140',
        unit: 'mg/dL',
        notes: '140–199 = impaired glucose tolerance; ≥ 200 = diabetes.',
      },
      {
        name: 'Fructosamine',
        normalRange: '200 – 285',
        unit: 'µmol/L',
        notes: 'Reflects glycemic control over 2–3 weeks. Useful when A1C is unreliable.',
      },
      {
        name: 'C-Peptide',
        normalRange: '0.5 – 2.0',
        unit: 'ng/mL',
        notes: 'Marker of endogenous insulin production. Helps differentiate T1 from T2 diabetes.',
      },
      {
        name: 'Insulin (fasting)',
        normalRange: '2 – 25',
        unit: 'µIU/mL',
        notes: 'Elevated in insulin resistance and insulinoma.',
      },
    ],
  },
];
